Developer
SergeyVoychenko/Full-Trafalgar pull request #1
Opened 2021-11-24 20:56 UTC by SergeyVoychenko

Completed construction.

2021-11-26 00:19 UTC, Rammfall requested changes

2021-11-26 00:19 UTC, Rammfall commented on css/styles.css
> +    min-width: 100vh;
Это не сильно имеет смысл, во первых когда ты поставил width, а во вторых какой смысл ставить vh что зависит от высоты на ширину

2021-11-26 00:19 UTC, Rammfall commented on css/styles.css
> +    width: 693px;
Используешь сильно глобальный селектор, любая картинка внутри контейнера будет иметь эту ширину

2021-11-26 00:19 UTC, Rammfall commented on css/styles.css
> +    content: attr(data-text);
Лучше удалять, чем оставлять комментарии, это считается грязным, мы комментим на этапе работы, а когда отправляем, нужно это убирать

2021-11-27 08:51 UTC, SergeyVoychenko commented on css/styles.css
> +    min-width: 100vh;
Спасибо, vh уберу (эксперементировал).

2021-11-27 10:51 UTC, merged